# This is the default config.yml
default-shop-account:
  name: ""
  is-free: true
text-color:
  bracket: dark purple
  command: white
  error: red
  normal: gold
  param: aqua
database-type: sqlite
items-db-path: plugins\DynamicMarket\
mysql:
  url: jdbc:mysql://localhost/minecraft
  engine: InnoDB
  user: root
  pass: pass
import-export:
  file: shopDB.csv
  path: plugins\DynamicMarket\
transaction-log:
  file: transactions.log
  autoflush: true
shop-tag: '{BKT}[{}Shop{BKT}]{}'
items-max-per:
  purchase: 64
  sale: 64
debug: false